version: '3'

services:
  app:
    image: com.crowdproj.marketplace/product-group-app-ktor:1.0-snapshot
    ports:
      - "8080:8080"
    depends_on:
      - fluent-bit
      - gremlin
    environment:
      - LOGS_FB_HOSTS=fluent-bit
      - LOGS_FB_PORT=24225
      - DB_TYPE_PROD=gremlin
      - DB_GREMLIN_HOST=gremlin
      - DB_GREMLIN_PORT=8182
      - DB_GREMLIN_USER=root
      - DB_GREMLIN_PASS=root_root

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      - "24225:24225"
      - "24225:24225/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=admin
    volumes:
      - ./volumes/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./volumes/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

  gremlin:
    image: "arcadedata/arcadedb:23.4.1"
    container_name: gremlin
    ports:
      - "2480:2480"
      - "2424:2424"
      - "8182:8182"
    volumes:
      - gremlin_data:/home/arcadedb/databases
    environment:
      JAVA_OPTS: "-Darcadedb.server.rootPassword=root_root -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin"

volumes:
  opensearch-data:
  gremlin_data: